// languageMap.ts

export const languageMap: { [key: string]: string } = {
    "Afrikaans": "af-ZA",
    "Albanian": "sq-AL",
    "Amharic": "am-ET",
    "Arabic": "ar-SA",
    "Armenian": "hy-AM",
    "Azerbaijani": "az-AZ",
    "Basque": "eu-ES",
    "Bengali": "bn-BD",
    "Bosnian": "bs-BA",
    "Bulgarian": "bg-BG",
    "Catalan": "ca-ES",
    "Chinese": "zh-CN",
    "Chinese (Hong Kong)": "zh-HK",
    "Chinese (Taiwan)": "zh-TW",
    "Croatian": "hr-HR",
    "Czech": "cs-CZ",
    "Danish": "da-DK",
    "Dutch": "nl-NL",
    "English": "en-US",
    "English (UK)": "en-GB",
    "English (Australia)": "en-AU",
    "Estonian": "et-EE",
    "Filipino": "fil-PH",
    "Finnish": "fi-FI",
    "French": "fr-FR",
    "Galician": "gl-ES",
    "Georgian": "ka-GE",
    "German": "de-DE",
    "Greek": "el-GR",
    "Gujarati": "gu-IN",
    "Hebrew": "he-IL",
    "Hindi": "hi-IN",
    "Hungarian": "hu-HU",
    "Icelandic": "is-IS",
    "Indonesian": "id-ID",
    "Italian": "it-IT",
    "Japanese": "ja-JP",
    "Javanese": "jv-ID",
    "Kannada": "kn-IN",
    "Kazakh": "kk-KZ",
    "Khmer": "km-KH",
    "Korean": "ko-KR",
    "Lao": "lo-LA",
    "Latvian": "lv-LV",
    "Lithuanian": "lt-LT",
    "Macedonian": "mk-MK",
    "Malay": "ms-MY",
    "Malayalam": "ml-IN",
    "Maltese": "mt-MT",
    "Marathi": "mr-IN",
    "Mongolian": "mn-MN",
    "Nepali": "ne-NP",
    "Norwegian": "no-NO",
    "Persian": "fa-IR",
    "Polish": "pl-PL",
    "Portuguese": "pt-PT",
    "Portuguese (Brazil)": "pt-BR",
    "Punjabi": "pa-IN",
    "Romanian": "ro-RO",
    "Russian": "ru-RU",
    "Serbian": "sr-RS",
    "Sinhala": "si-LK",
    "Slovak": "sk-SK",
    "Slovenian": "sl-SI",
    "Spanish": "es-ES",
    "Spanish (Mexico)": "es-MX",
    "Swahili": "sw-TZ",
    "Swedish": "sv-SE",
    "Tamil": "ta-IN",
    "Telugu": "te-IN",
    "Thai": "th-TH",
    "Turkish": "tr-TR",
    "Ukrainian": "uk-UA",
    "Urdu": "ur-PK",
    "Uzbek": "uz-UZ",
    "Vietnamese": "vi-VN",
    "Zulu": "zu-ZA",
  };
  